version: '3.8'

services:
  nodo-a:
    build: .
    container_name: todo-nodo-a
    ports:
      - "8001:5000"
    environment:
      - NODO_NAME=Nodo A
      - PORT=5000
    volumes:
      - ./data:/app/data

  nodo-b:
    build: .
    container_name: todo-nodo-b
    ports:
      - "8002:5000"
    environment:
      - NODO_NAME=Nodo B
      - PORT=5000
    volumes:
      - ./data:/app/data